version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.10.1
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn package cache
          keys:
            - yarn-packages-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn package cache
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run:
          name: Build
          command: npm run build

workflows:
  version: 2
  build_test_publish:
    jobs:
      - build
