version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.10.1
    steps:
      - checkout
      - restore_cache:
          name: Restore dependency cache
          key: dependency-cache-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save depedency cache
          key: dependency-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: npm run build
      - save_cache:
          name: Save build output cache
          key: build-output-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - dist
            - lib
            - es
  test:
    docker:
      - image: circleci/node:9.10.1
    steps:
      - checkout
      - restore_cache:
          name: Restore dependency cache
          keys:
            - dependency-cache-v1-{{ checksum "yarn.lock" }}
      - restore_cache:
          name: Restore build results cache
          key: build-output-v1-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Run unit tests
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT: reports/junit/js-test-results.xml
      - run:
          name: Run linters
          command: npm run lint
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  publish:
    docker:
      - image: circleci/node:9.10.1
    steps:
      - checkout
      - restore_cache:
          name: Restore build results cache
          key: build-output-v1-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          name: Restore dependency cache
          keys:
            - dependency-cache-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Prepare NPM auth token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish to npm
          command: npm run publish



workflows:
  version: 2
  build_test_publish:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - master
